# See: Travis Support did recomment moving Android builds to GCE.
# Which is on 'precise' and has larger VMs: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: precise

language: android

jdk:
  - oraclejdk8
  - oraclejdk7

notifications:
  irc: "irc.freenode.org#aerogear"

android:
  components:
    - build-tools-23.0.3
    - android-23

env:
    matrix:
      - ANDROID_TARGET=android-23

before_install:

  #################################################
  ########## maven-android-sdk-deployer ###########
  #################################################

  # Checkout maven-android-sdk-deployer
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git

  # Install android maven repository
  - cd $PWD/maven-android-sdk-deployer/platforms/$ANDROID_TARGET
  - mvn  install -N --quiet
  - cd -
